### ISSUE TITLE
[bug] [docs] Images not rendering

### ISSUE THREAD

**Issue by pr3mar** [amejiarosario/dsa.js#3]
Hey, I just noticed that the paths are misconfigured in the docs, example:
![image](https://user-images.githubusercontent.com/5265944/55710542-1bcb3680-59eb-11e9-9ef1-1cbddc78020c.png)

**Comment by amejiarosario** [comment]
Github has some issues with the paths on the asciiDoc format. I'll fix it

**Comment by amejiarosario** [comment]
@pr3mar It's fixed now. Check out the images https://github.com/amejiarosario/dsa.js/blob/master/book/chapters/linked-list.adoc
