### ISSUE TITLE
What if value in array is '-1'?

### ISSUE THREAD

**Issue by ofca** [amejiarosario/dsa.js#5]
I mean, what if array is something like: 

`const arr = [3, 4, -1, 3]`

then this:

`searchByIndex(arr, 2)` will return `-1`

https://github.com/amejiarosario/dsa.js/blob/bb003f18651670dfd223452f8693b7b67f0f3b4d/src/data-structures/arrays/array.js#L48

**Comment by amejiarosario** [comment]
That's a good point. I'll make a fix for it

**Comment by amejiarosario** [comment]
Fixed with 2b94d37027486063f106bea25f7128b74fa19795. It will return `undefined` so -1 can also be in the array
